// Seed/demo data for the application when no backend is connected

export const DOCUMENT_TYPES = [
  { id: 'hc_petition', name: 'Petition for Writ of Habeas Corpus', category: 'petition' },
  { id: 'js44', name: 'Civil Cover Sheet (JS 44)', category: 'filing' },
  { id: 'osc', name: 'Proposed Order to Show Cause', category: 'motion' },
  { id: 'tro', name: 'Emergency TRO Motion', category: 'motion' },
  { id: 'attorney_decl', name: 'Attorney Declaration', category: 'filing' },
  { id: 'reply_brief', name: 'Reply Brief', category: 'brief' },
];

export const VARIABLE_GROUPS = [
  {
    name: 'Petitioner',
    variables: [
      'PETITIONER_NAME', 'PETITIONER_COUNTRY', 'ENTRY_DATE', 'YEARS_RESIDENCE',
      'APPREHENSION_LOCATION', 'APPREHENSION_DATE', 'CRIMINAL_HISTORY', 'COMMUNITY_TIES',
    ],
  },
  {
    name: 'Detention',
    variables: [
      'DETENTION_FACILITY', 'FACILITY_LOCATION', 'WARDEN_NAME', 'DETENTION_DAYS',
    ],
  },
  {
    name: 'Court',
    variables: [
      'DISTRICT_FULL', 'DIVISION', 'COURT_LOCATION', 'CASE_NUMBER', 'JUDGE_CODE', 'FILING_DATE',
    ],
  },
  {
    name: 'Officials',
    variables: [
      'FOD_NAME', 'FIELD_OFFICE', 'ICE_DIRECTOR', 'DHS_SECRETARY', 'AG_NAME',
    ],
  },
  {
    name: 'Attorneys',
    variables: [
      'ATTORNEY_1_NAME', 'ATTORNEY_1_BAR', 'ATTORNEY_1_FIRM', 'ATTORNEY_1_ADDR',
      'ATTORNEY_1_PHONE', 'ATTORNEY_1_EMAIL',
      'ATTORNEY_2_NAME', 'ATTORNEY_2_BAR', 'ATTORNEY_2_FIRM', 'ATTORNEY_2_ADDR',
      'ATTORNEY_2_PHONE', 'ATTORNEY_2_EMAIL',
    ],
  },
];

export const SEED_TEMPLATES = [
  {
    id: 'tpl_hc_general',
    name: 'HC Petition (General)',
    category: 'petition',
    desc: 'Standard \u00A7 2241 habeas corpus petition \u2014 Yajure Hurtado framework',
    docs: 12,
    lastUsed: Date.now() - 2 * 86400000,
    sections: [
      { id: 's1', name: 'Introduction', required: true, paraCount: 5, content: '1. Petitioner-Plaintiff {{PETITIONER_NAME}} ("Petitioner") is a citizen of {{PETITIONER_COUNTRY}} who has made his home in the United States for {{YEARS_RESIDENCE}} years...' },
      { id: 's2', name: 'Custody', required: true, paraCount: 1, content: '2. Petitioner is currently detained at {{DETENTION_FACILITY}} in {{FACILITY_LOCATION}}, under the custody of Respondent {{WARDEN_NAME}}.' },
      { id: 's3', name: 'Jurisdiction', required: true, paraCount: 3, content: '3. This Court has jurisdiction pursuant to 28 U.S.C. \u00A7 2241...' },
      { id: 's4', name: 'Requirements of \u00A7\u00A7 2241, 2243', required: true, paraCount: 2, content: '4. This Petition satisfies the requirements of 28 U.S.C. \u00A7\u00A7 2241 and 2243...' },
      { id: 's5', name: 'Venue', required: true, paraCount: 1, content: '5. Venue is proper in this district because Petitioner is detained within the {{DISTRICT_FULL}}.' },
      { id: 's6', name: 'Exhaustion', required: true, paraCount: 3, content: '6. Petitioner is not required to exhaust administrative remedies before seeking habeas relief...' },
      { id: 's7', name: 'Parties', required: true, paraCount: 6, content: '7. Petitioner {{PETITIONER_NAME}} is a citizen of {{PETITIONER_COUNTRY}} who entered the United States on {{ENTRY_DATE}}...' },
      { id: 's8', name: 'Legal Background', required: true, paraCount: 15, content: '8. The Immigration and Nationality Act provides for the detention of noncitizens...' },
      { id: 's9', name: 'Statement of Facts', required: true, paraCount: 7, content: '9. On {{APPREHENSION_DATE}}, Petitioner was apprehended by ICE agents at {{APPREHENSION_LOCATION}}...' },
      { id: 's10', name: 'Count I \u2014 \u00A7 1226(a)', required: true, paraCount: 5, content: '10. Petitioner reasserts and incorporates the foregoing paragraphs as though fully set forth herein...' },
      { id: 's11', name: 'Count II \u2014 Bond Regs', required: true, paraCount: 3, content: '11. The regulations governing bond determinations violate Petitioner\'s rights...' },
      { id: 's12', name: 'Count III \u2014 Due Process', required: true, paraCount: 9, content: '12. Petitioner\'s continued detention without adequate process violates the Due Process Clause...' },
      { id: 's13', name: 'Count IV \u2014 Prolonged Detention', required: false, paraCount: 4, content: '13. Petitioner has been detained for {{DETENTION_DAYS}} days without a hearing...', condition: 'DETENTION_DAYS > 180' },
      { id: 's14', name: 'Prayer for Relief', required: true, paraCount: 1, content: 'WHEREFORE, Petitioner respectfully requests that this Court: (a) Issue the Writ...' },
      { id: 's15', name: 'Verification', required: true, paraCount: 2, content: 'I, {{PETITIONER_NAME}}, hereby verify under penalty of perjury...' },
    ],
    variables: VARIABLE_GROUPS.flatMap(g => g.variables),
  },
  {
    id: 'tpl_hc_9th',
    name: 'HC Petition (9th Circuit)',
    category: 'petition',
    desc: 'Adapted for 9th Circuit local rules and additional precedent',
    docs: 3,
    lastUsed: Date.now() - 7 * 86400000,
    sections: [
      { id: 's1', name: 'Introduction', required: true, paraCount: 6, content: '' },
      { id: 's2', name: 'Custody', required: true, paraCount: 1, content: '' },
      { id: 's3', name: 'Jurisdiction', required: true, paraCount: 4, content: '' },
    ],
    variables: VARIABLE_GROUPS.flatMap(g => g.variables).concat(['NINTH_CIRCUIT_CASE']),
  },
  {
    id: 'tpl_js44',
    name: 'Civil Cover Sheet (JS 44)',
    category: 'filing',
    desc: 'Standard federal civil cover sheet',
    docs: 8,
    lastUsed: Date.now() - 2 * 86400000,
    sections: [
      { id: 's1', name: 'Cover Sheet Fields', required: true, paraCount: 1, content: '' },
    ],
    variables: ['PETITIONER_NAME', 'DISTRICT_FULL', 'CASE_NUMBER', 'FILING_DATE', 'ATTORNEY_1_NAME', 'ATTORNEY_1_BAR', 'ATTORNEY_1_FIRM', 'ATTORNEY_1_ADDR', 'ATTORNEY_1_PHONE', 'ATTORNEY_1_EMAIL', 'WARDEN_NAME', 'FACILITY_LOCATION'],
  },
  {
    id: 'tpl_osc',
    name: 'Proposed Order to Show Cause',
    category: 'motion',
    desc: 'Proposed order for TRO / OSC with standard language',
    docs: 7,
    lastUsed: Date.now() - 3 * 86400000,
    sections: [
      { id: 's1', name: 'Order Header', required: true, paraCount: 1, content: '' },
      { id: 's2', name: 'Order Body', required: true, paraCount: 2, content: '' },
      { id: 's3', name: 'Signature Block', required: true, paraCount: 1, content: '' },
    ],
    variables: ['PETITIONER_NAME', 'WARDEN_NAME', 'CASE_NUMBER', 'DISTRICT_FULL', 'JUDGE_CODE'],
  },
  {
    id: 'tpl_tro',
    name: 'Emergency TRO Motion',
    category: 'motion',
    desc: 'Motion for temporary restraining order \u2014 transfer prevention',
    docs: 4,
    lastUsed: Date.now() - 14 * 86400000,
    sections: [
      { id: 's1', name: 'Introduction', required: true, paraCount: 2, content: '' },
      { id: 's2', name: 'Statement of Facts', required: true, paraCount: 3, content: '' },
      { id: 's3', name: 'Legal Standard', required: true, paraCount: 2, content: '' },
      { id: 's4', name: 'Argument', required: true, paraCount: 4, content: '' },
      { id: 's5', name: 'Irreparable Harm', required: true, paraCount: 2, content: '' },
      { id: 's6', name: 'Conclusion', required: true, paraCount: 1, content: '' },
    ],
    variables: ['PETITIONER_NAME', 'DETENTION_FACILITY', 'FACILITY_LOCATION', 'WARDEN_NAME', 'CASE_NUMBER', 'DISTRICT_FULL', 'APPREHENSION_DATE', 'COMMUNITY_TIES', 'FOD_NAME', 'FIELD_OFFICE', 'ICE_DIRECTOR', 'DHS_SECRETARY', 'ATTORNEY_1_NAME', 'ATTORNEY_1_BAR', 'ATTORNEY_1_FIRM', 'ATTORNEY_1_ADDR', 'ATTORNEY_1_PHONE', 'ATTORNEY_1_EMAIL'],
  },
  {
    id: 'tpl_atty_decl',
    name: 'Attorney Declaration',
    category: 'filing',
    desc: 'Declaration in support of habeas petition',
    docs: 6,
    lastUsed: Date.now() - 5 * 86400000,
    sections: [
      { id: 's1', name: 'Declaration Header', required: true, paraCount: 1, content: '' },
      { id: 's2', name: 'Background', required: true, paraCount: 2, content: '' },
      { id: 's3', name: 'Facts Attested', required: true, paraCount: 3, content: '' },
      { id: 's4', name: 'Verification', required: true, paraCount: 1, content: '' },
    ],
    variables: ['PETITIONER_NAME', 'DETENTION_FACILITY', 'ATTORNEY_1_NAME', 'ATTORNEY_1_BAR', 'ATTORNEY_1_FIRM', 'CASE_NUMBER', 'DISTRICT_FULL', 'FILING_DATE'],
  },
  {
    id: 'tpl_reply',
    name: 'Reply Brief',
    category: 'brief',
    desc: 'Reply to government\'s response \u2014 template with conditional sections',
    docs: 2,
    lastUsed: Date.now() - 21 * 86400000,
    sections: [
      { id: 's1', name: 'Introduction', required: true, paraCount: 2, content: '' },
      { id: 's2', name: 'Procedural History', required: true, paraCount: 2, content: '' },
      { id: 's3', name: 'Argument I', required: true, paraCount: 4, content: '' },
      { id: 's4', name: 'Argument II', required: true, paraCount: 3, content: '' },
      { id: 's5', name: 'Argument III', required: false, paraCount: 3, content: '', condition: 'HAS_DUE_PROCESS_CLAIM' },
      { id: 's6', name: 'Argument IV', required: false, paraCount: 2, content: '', condition: 'DETENTION_DAYS > 180' },
      { id: 's7', name: 'Conclusion', required: true, paraCount: 1, content: '' },
      { id: 's8', name: 'Certificate of Service', required: true, paraCount: 1, content: '' },
    ],
    variables: ['PETITIONER_NAME', 'CASE_NUMBER', 'DISTRICT_FULL', 'JUDGE_CODE', 'ATTORNEY_1_NAME', 'ATTORNEY_1_BAR', 'ATTORNEY_1_FIRM', 'WARDEN_NAME', 'DETENTION_FACILITY', 'DETENTION_DAYS', 'APPREHENSION_DATE', 'ICE_DIRECTOR', 'DHS_SECRETARY', 'AG_NAME', 'FOD_NAME', 'FILING_DATE', 'PETITIONER_COUNTRY', 'ENTRY_DATE', 'YEARS_RESIDENCE', 'COMMUNITY_TIES', 'CRIMINAL_HISTORY', 'FACILITY_LOCATION'],
  },
];

export const SEED_CASES = [
  {
    id: 'case_rivera',
    petitionerName: 'Rivera, Juan Jose',
    stage: 'Attorney Review',
    circuit: '4th Cir.',
    facility: 'Farmville DC',
    facilityLocation: 'Farmville, VA',
    daysInStage: 3,
    owner: '@katie:app.aminoimmigration.com',
    lastUpdated: new Date().toISOString(),
    variables: {
      PETITIONER_NAME: 'Juan Jose Rivera',
      PETITIONER_COUNTRY: 'Honduras',
      ENTRY_DATE: '2019-03-15',
      YEARS_RESIDENCE: '6',
      APPREHENSION_LOCATION: 'Richmond, VA',
      APPREHENSION_DATE: '2024-10-03',
      CRIMINAL_HISTORY: 'None',
      COMMUNITY_TIES: 'Employed at Riverside Construction for 4 years. Two U.S. citizen children enrolled at Farmville Elementary.',
      DETENTION_FACILITY: 'Farmville Detention Center',
      FACILITY_LOCATION: 'Farmville, VA',
      WARDEN_NAME: 'John Smith',
      DETENTION_DAYS: '45',
      DISTRICT_FULL: 'Eastern District of Virginia',
      DIVISION: 'Richmond Division',
      COURT_LOCATION: 'Richmond, VA',
      CASE_NUMBER: '',
      JUDGE_CODE: '',
      FILING_DATE: '',
      FOD_NAME: 'Sarah Johnson',
      FIELD_OFFICE: 'Washington DC Field Office',
      ICE_DIRECTOR: 'Patrick Lechleitner',
      DHS_SECRETARY: 'Alejandro Mayorkas',
      AG_NAME: 'Merrick Garland',
      ATTORNEY_1_NAME: 'Katie Soltis',
      ATTORNEY_1_BAR: 'VA 12345',
      ATTORNEY_1_FIRM: 'Amino Immigration Law',
      ATTORNEY_1_ADDR: '123 Main St, Richmond, VA 23219',
      ATTORNEY_1_PHONE: '(804) 555-0123',
      ATTORNEY_1_EMAIL: 'katie@aminoimmigration.com',
      ATTORNEY_2_NAME: '',
      ATTORNEY_2_BAR: '',
      ATTORNEY_2_FIRM: '',
      ATTORNEY_2_ADDR: '',
      ATTORNEY_2_PHONE: '',
      ATTORNEY_2_EMAIL: '',
    },
    documents: [
      { id: 'doc_1', templateId: 'tpl_hc_general', name: 'Petition for Writ of Habeas Corpus', status: 'review', sections: [] },
      { id: 'doc_2', templateId: 'tpl_js44', name: 'Civil Cover Sheet (JS 44)', status: 'draft', sections: [] },
      { id: 'doc_3', templateId: 'tpl_osc', name: 'Proposed Order to Show Cause', status: 'ready', sections: [] },
      { id: 'doc_4', templateId: null, name: 'Emergency TRO Motion', status: 'empty', sections: [] },
      { id: 'doc_5', templateId: 'tpl_atty_decl', name: 'Attorney Declaration', status: 'draft', sections: [] },
    ],
    comments: [
      { id: 'cmt_1', documentId: 'doc_1', section: 'INTRODUCTION', author: 'K. Soltis', text: 'Confirm apprehension date \u2014 client says Oct 2 but I-213 says Oct 3.', status: 'open', createdAt: Date.now() - 3600000 },
      { id: 'cmt_2', documentId: 'doc_1', section: 'FACTS \u00B642', author: 'K. Soltis', text: 'Strengthen community ties \u2014 mention employer by name and children\'s school.', status: 'open', createdAt: Date.now() - 1800000 },
    ],
  },
  {
    id: 'case_mendoza',
    petitionerName: 'Mendoza, Carlos',
    stage: 'Drafting',
    circuit: '11th Cir.',
    facility: 'Stewart DC',
    facilityLocation: 'Lumpkin, GA',
    daysInStage: 1,
    owner: '@katie:app.aminoimmigration.com',
    lastUpdated: new Date().toISOString(),
    variables: {
      PETITIONER_NAME: 'Carlos Mendoza',
      PETITIONER_COUNTRY: 'Guatemala',
      ENTRY_DATE: '2020-06-22',
      YEARS_RESIDENCE: '5',
      APPREHENSION_LOCATION: 'Atlanta, GA',
      APPREHENSION_DATE: '2024-11-15',
      CRIMINAL_HISTORY: 'None',
      COMMUNITY_TIES: 'Attends local church. Partner is legal permanent resident.',
      DETENTION_FACILITY: 'Stewart Detention Center',
      FACILITY_LOCATION: 'Lumpkin, GA',
      WARDEN_NAME: 'Michael Davis',
      DETENTION_DAYS: '30',
      DISTRICT_FULL: 'Middle District of Georgia',
      DIVISION: '',
      COURT_LOCATION: 'Macon, GA',
      CASE_NUMBER: '',
      JUDGE_CODE: '',
      FILING_DATE: '',
    },
    documents: [
      { id: 'doc_m1', templateId: 'tpl_hc_general', name: 'Petition for Writ of Habeas Corpus', status: 'draft', sections: [] },
      { id: 'doc_m2', templateId: null, name: 'Civil Cover Sheet (JS 44)', status: 'empty', sections: [] },
      { id: 'doc_m3', templateId: null, name: 'Proposed Order to Show Cause', status: 'empty', sections: [] },
      { id: 'doc_m4', templateId: null, name: 'Emergency TRO Motion', status: 'empty', sections: [] },
      { id: 'doc_m5', templateId: null, name: 'Attorney Declaration', status: 'empty', sections: [] },
    ],
    comments: [],
  },
  {
    id: 'case_alvarez',
    petitionerName: 'Alvarez, Maria',
    stage: 'Filed',
    circuit: '9th Cir.',
    facility: 'Eloy DC',
    facilityLocation: 'Eloy, AZ',
    daysInStage: 12,
    owner: '@katie:app.aminoimmigration.com',
    lastUpdated: new Date().toISOString(),
    variables: {
      PETITIONER_NAME: 'Maria Alvarez',
      PETITIONER_COUNTRY: 'Mexico',
      ENTRY_DATE: '2017-01-10',
      YEARS_RESIDENCE: '8',
      APPREHENSION_LOCATION: 'Phoenix, AZ',
      APPREHENSION_DATE: '2024-09-20',
      CRIMINAL_HISTORY: 'None',
      COMMUNITY_TIES: 'Three U.S. citizen children. Active member of St. Thomas Church. Employed at Desert Valley Nursery.',
      DETENTION_FACILITY: 'Eloy Detention Center',
      FACILITY_LOCATION: 'Eloy, AZ',
      WARDEN_NAME: 'Robert Martinez',
      DETENTION_DAYS: '90',
      DISTRICT_FULL: 'District of Arizona',
      DIVISION: 'Phoenix Division',
      COURT_LOCATION: 'Phoenix, AZ',
      CASE_NUMBER: '2:24-cv-02345-PHX',
      JUDGE_CODE: 'DLR',
      FILING_DATE: '2024-11-05',
    },
    documents: [
      { id: 'doc_a1', templateId: 'tpl_hc_9th', name: 'Petition for Writ of Habeas Corpus', status: 'ready', sections: [] },
      { id: 'doc_a2', templateId: 'tpl_js44', name: 'Civil Cover Sheet (JS 44)', status: 'ready', sections: [] },
      { id: 'doc_a3', templateId: 'tpl_osc', name: 'Proposed Order to Show Cause', status: 'ready', sections: [] },
      { id: 'doc_a4', templateId: 'tpl_tro', name: 'Emergency TRO Motion', status: 'ready', sections: [] },
      { id: 'doc_a5', templateId: 'tpl_atty_decl', name: 'Attorney Declaration', status: 'ready', sections: [] },
    ],
    comments: [],
  },
];

// Additional pipeline cases for the kanban view
export const SEED_PIPELINE_EXTRA = [
  {
    id: 'case_dominguez',
    petitionerName: 'Dominguez, P.',
    stage: 'Intake',
    circuit: '5th Cir.',
    facility: 'South Texas DC',
    facilityLocation: 'Pearsall, TX',
    daysInStage: 1,
    documents: [
      { id: 'doc_d1', status: 'empty', name: 'Petition' },
      { id: 'doc_d2', status: 'empty', name: 'Cover Sheet' },
      { id: 'doc_d3', status: 'empty', name: 'OSC' },
      { id: 'doc_d4', status: 'empty', name: 'TRO Motion' },
      { id: 'doc_d5', status: 'empty', name: 'Attorney Decl.' },
    ],
    variables: {},
    comments: [],
  },
  {
    id: 'case_torres',
    petitionerName: 'Torres, R.',
    stage: 'Drafting',
    circuit: '3rd Cir.',
    facility: 'York County DC',
    facilityLocation: 'York, PA',
    daysInStage: 4,
    documents: [
      { id: 'doc_t1', status: 'ready', name: 'Petition' },
      { id: 'doc_t2', status: 'ready', name: 'Cover Sheet' },
      { id: 'doc_t3', status: 'draft', name: 'OSC' },
      { id: 'doc_t4', status: 'empty', name: 'TRO Motion' },
      { id: 'doc_t5', status: 'empty', name: 'Attorney Decl.' },
    ],
    variables: {},
    comments: [],
  },
  {
    id: 'case_guzman',
    petitionerName: 'Guzman, L.',
    stage: 'Ready to File',
    circuit: '6th Cir.',
    facility: 'Morrow County DC',
    facilityLocation: 'Mt. Gilead, OH',
    daysInStage: 2,
    documents: [
      { id: 'doc_g1', status: 'ready', name: 'Petition' },
      { id: 'doc_g2', status: 'ready', name: 'Cover Sheet' },
      { id: 'doc_g3', status: 'ready', name: 'OSC' },
      { id: 'doc_g4', status: 'ready', name: 'TRO Motion' },
      { id: 'doc_g5', status: 'ready', name: 'Attorney Decl.' },
    ],
    variables: {},
    comments: [],
  },
  {
    id: 'case_chen',
    petitionerName: 'Chen, W.',
    stage: 'Filed',
    circuit: '2nd Cir.',
    facility: 'Bergen County DC',
    facilityLocation: 'Hackensack, NJ',
    daysInStage: 8,
    documents: [
      { id: 'doc_c1', status: 'ready', name: 'Petition' },
      { id: 'doc_c2', status: 'ready', name: 'Cover Sheet' },
      { id: 'doc_c3', status: 'ready', name: 'OSC' },
      { id: 'doc_c4', status: 'ready', name: 'TRO Motion' },
      { id: 'doc_c5', status: 'ready', name: 'Attorney Decl.' },
    ],
    variables: {},
    comments: [],
  },
];
